### PR TITLE
A new version 3.6.1

### PR DESCRIPTION
**Pull request by AlexAv**
New features:

    Themes support.
    Theme with sidebar. Good for widescreens and tablets.
    'Sakura' theme.
    'Is Sorted' parameter for Enum fields. Sorts list alphabetically.
    Record count now can be displayed on list view (configurable in Administration > User Interface).
    Ability to create new records from dashlets.
    'Multiple Attachments' field type.
    User receives notification if any followed entity gets removed by someone.
    Ability to keep fetched emails unread on imap server.
    Audited option for fields now is available in Entity Manager. Allows to see a history of changes in Stream panel.
    Case can be related with multiple Contacts.
    Improved Global Search.
    Improved navigation bar for small screen sizes.
    'Last 7 Days' filter for date and datetime fields.
    Layout Manager: ability to reset to default.
    Stream panel filter.
    When user changes own password the current password must be entered.
    DetailSmall layouts now has 2-columns.
    Ability to edit entity list of parent fields.
    Document Folders.
    Activities and History panels on the user's detail view. Access to these panels is controlled by new parameter 'User Permission' in Roles.
    Followers are shown on a detail view.
    Ability to create Case from Email manually.
    Ability to reply on Email right from History panel.
    Ability to unlink all entries from Target List.
    Improved filter for enum fields.
    UI of filters is improved.
    Default reminders in Preferences.
    Email improvements.
    Varchar type filter improvement.
    Date completed field in Task.
    Attachments field added to Task.
    Calendar view mode now is remembered.
    Ability to filter only followed records.
    Ability to filter emails by user.
    Entity Manager: Ability to setup a default sorting for list views.

### CODE REVIEW

**Comment by JedMeister** [comment]
Hey @AlexAv, 

Thanks so much for your update. Sorry that it has taken so long for us to release... We have suffered from a bit of feature creep and some infrastructure issues but I'm pretty sure that we're back on track now... 

Did you test that everything still works ok? I had one of our guys create some inithooks so the password is set at firstboot. So long as there have not been major internal changes it should still all work hopefully but confirmation would be a bonus! :smile:

**Comment by AlexAv** [comment]
Hi @JedMeister ,

turnkey

As I removed my TKLDev. I'm trying to do a fresh installation.
And had no luck for **core** example 

cd core
make

What it can be?

Thanks,
Alex

**Comment by JedMeister** [comment]
Hey Alex,
I'd run `make clean` first and try again. It's not finding the package `isolinux` which is needed to make the ISO at the end. If the same error happens again then my next guess is network issue. FWIW the build env hardcodes use of google DNS (8.8.8.8.8 & 8.8.4.4) so if it is running behind a proxy and/or firewall somewhere then it possibly can't find the DNS?

**Comment by JedMeister** [comment]
Also @AlexAv - meant to mention the EspoCRM code is now (finally) in the TurnKey library: https://github.com/turnkeylinux-apps/espocrm 

Ready for the final v14.0 build (coming real soon!)

Probably best to do future updates, PRs, etc against that one.

**Comment by AlexAv** [comment]
Hi @JedMeister,

My solution was to use last tkldev (14.0rc1).
A Linux and EspoCRM was installed successfully. Just one thing, in what moment this hook should be triggered **/overlay/usr/lib/inithooks/bin/espocrm.py** ?

Thanks for publishing espocrm in the main repository.

**Comment by JedMeister** [comment]
Either manually via `turnkey-init` or when the appliance first boots.

**Comment by AlexAv** [comment]
Thanks @JedMeister, 

After installation I didn't find how to set a password for espocrm. 
Could you check please?

Last message box what I saw.
turnkey

**Comment by JedMeister** [comment]
Hmmm... I'll need to have a closer look...

**Comment by JedMeister** [comment]
EspoCRM seems to be working fine for me now. I have done some tweaks so if you want to test again try the main repo: https://github.com/turnkeylinux-apps/espocrm I have also made it so it generates a unique random password salt on firstboot too. 

Also I'll be deleting this repo soon; for all future updates please do PRs against the main turnkey repo.

**Comment by AlexAv** [comment]
It works now! Thank you very much.

**Pull request merged**
